name: Build and Rollout Kanvas
on:
  workflow_call:
    inputs:
      branch:
        description: Repository branch to build.
        type: string
        default: master
  workflow_dispatch:
    inputs:
      branch:
        description: Repository branch to build.
        type: string
        default: master
      version:
        description: "Version of Meshery (e.g. v0.0.0)"
        type: string
        required: false
      revision:
        description: "Revision of Extension (e.g. 1)"
        type: string
        required: false
jobs:
  build-and-release:
    name: Build and Rollout Kanvas
    env:
      RELEASE_CHANNEL: "kanvas"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout meshery/meshery
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: "meshery"
          repository: meshery/meshery
          ref: ${{ inputs.branch }}

      - name: Fetch `get-meshery-version` script from meshery-extensions.
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: layer5labs/meshery-extensions
          path: "meshery-extensions"
          fetch-depth: 1
          sparse-checkout: |
            build/get-meshery-version
            build/get-extension-version
          sparse-checkout-cone-mode: false

      - name: File system view
        run: |
          pwd;
          ls;

      - name: Fetch Meshery and Extensions version
        run: |
          chmod +x ./meshery-extensions/build/get-meshery-version
          MESHERY_VERSION=$(./meshery-extensions/build/get-meshery-version)
          echo "MESHERY_VERSION=$MESHERY_VERSION" >> $GITHUB_ENV

          chmod +x ./meshery-extensions/build/get-extension-version
          MESHERY_VERSION=$(./meshery-extensions/build/get-extension-version)
          echo "MESHERY_EXTENSION_VERSION=$MESHERY_EXTENSION_VERSION" >> $GITHUB_ENV

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure Meshery UI
        working-directory: "./meshery"
        run: |
          cat << EOF > ui/ui.config.js
          module.exports = {
            components: {
              navigator: false, // set false to disable the navigator component ( default: true )
            },
          };
          EOF
      
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: layer5/meshery
          tags: |
            type=raw,value=${{env.RELEASE_CHANNEL}}-{{sha}}
            type=semver,pattern={{version}},value=${{env.MESHERY_VERSION}}
            type=raw,value=${{env.RELEASE_CHANNEL}}-{{tag}}
    
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: install/docker/.
          build-args: |
            TOKEN=${{ secrets.GLOBAL_TOKEN }}
            GIT_COMMITSHA=${GITHUB_SHA::8}
            GIT_VERSION=${{ env.MESHERY_VERSION }}
            RELEASE_CHANNEL=${env.RELEASE_CHANNEL}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64

      - name: Bundle kanvas extension with the image
        working-directory: "meshery-extensions-packages"
        run: |
          wget https://github.com/layer5labs/meshery-extensions-packages/releases/download/${{ env.MESHERY_EXTENSION_VERSION }}/provider-meshery.tar.gz

          mkdir extensions-package
          tar xzf provider-meshery.tar.gz -C extensions-package 
          mkdir -p provider/Meshery/${{ env.MESHERY_EXTENSION_VERSION }}
          mv extensions-package provider/Meshery/${{ env.MESHERY_EXTENSION_VERSION }}

          ls;

          docker run -d --name meshery-tmp layer5/meshery:kanvas-latest

          docker cp ./Meshery meshery-tmp:/home/appuser/.meshery/provider/Meshery

          docker container commit meshery-tmp layer5/meshery:kanvas-latest

      - name: Docker tag & push
        run: |

          docker tag layer5/meshery:kanvas-latest layer5/meshery:kanvas-${GITHUB_SHA::8}
          docker tag layer5/meshery:kanvas-latest layer5/meshery:kanvas-${{ env.MESHERY_VERSION }}

          docker push layer5/meshery:kanvas-latest

          docker push layer5/meshery:kanvas-${GITHUB_SHA::8}
          docker push layer5/meshery:kanvas-${{ env.MESHERY_VERSION }}

      - name: Rollout Kanvas
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.METAL03_HOST }}
          username: ${{ secrets.METAL03_USERNAME }}
          key: ${{ secrets.METAL03_KEY }}
          port: 22
          script: |
            kubectl set image deployment/meshery meshery=layer5/meshery:kanvas-${{env.MESHERY_VERSION}} -n meshery-extensions
