name: Release and Deploy Meshery Cloud
on:
  workflow_call:
    inputs:
      release-environment: 
        description: "Staging or Production (lowercase)"
        required: true
        default: "staging"
        type: string
      release-version:
        description: "e.g. v0.6.26"
        required: true
        default: "latest"
        type: string
      branch:
        description: "Branch to deploy in the staging environment. If not provided, master branch of the repository will be used."
        default: "master"
        type: string
    secrets:
      GH_ACCESS_TOKEN: 
        required: true
      DOCKER_USERNAME: 
        required: true
      DOCKER_PASSWORD: 
        required: true
      MESHERY_CLOUD_AWS_PROD_USERNAME:
        required: true
      MESHERY_CLOUD_AWS_STG_HOST:
        required: true
      MESHERY_CLOUD_AWS_PROD_HOST:
        required: true
      MESHERY_CLOUD_AWS_PROD_KEY:
        required: true
      GLOBAL_TOKEN:
        required: true
      METAL03_HOST:
        required: true
      METAL03_KEY:
        required: true
      METAL03_USERNAME:
        required: true

  workflow_dispatch:
    inputs:
      release-environment: 
        description: "Staging or Production (lowercase)"
        required: true
        default: "staging"
      release-version: 
        description: "e.g. v0.6.26"
        required: true
        default: "latest"
      branch:
        description: "Branch to deploy in the staging environment. If not provided, master branch of the repository will be used."
        default: "master"
        type: string

env:
  GIT_VERSION: ${{inputs.release-version}}

jobs:
  update-doc-release-version:
    name: API Docs
    if: inputs.release-environment == 'production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Meshery Cloud code
        uses: actions/checkout@v4
        with:
          repository: layer5io/meshery-cloud
          fetch-depth: 1
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: API Docs - Install Redocly
        uses: actions/setup-node@v4
      - run: npm i -g @redocly/cli@latest
      - name: API Docs - Update schema.yml
        uses: fjogeleit/yaml-update-action@v0.15.0
        with:
          repository: l5io/meshery-cloud
          branch: master
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          valueFile: 'models/openapi-schema/schema.yml'
          commitChange: true
          propertyPath: 'info.version'
          value: ${{inputs.release-version}}
          message: Updated meshery-cloud version to ${{inputs.release-version}}
          commitUserName: l5io
          commitUserEmail: l5io@layer5.io
      
  lint-fix:
    name: Lint UI and Backend
    if: inputs.release-environment == 'staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Meshery Cloud code
        uses: actions/checkout@v4
        with:
          path: meshery-cloud
          repository: layer5io/meshery-cloud
          fetch-depth: 1
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          ref: ${{ inputs.branch }}
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'
      - name: Install prettier and eslint
        run: |
           npm i -g prettier;
           npm i -g eslint;
      - name: Lint UI and Backend
        run: |
          cd meshery-cloud
          make ui-lint-fix
          make cloud-lint-fix
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: l5io
          commit_user_email: l5io@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: '[CI] Lint fix backend/ui'
          repository: meshery-cloud

  staging:
    needs: update-doc-release-version
    if: always() && inputs.release-environment == 'staging' 
    name: Staging - Docker build and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Meshery Cloud code
      uses: actions/checkout@v4
      with:
        path: meshery-cloud
        repository: layer5io/meshery-cloud
        fetch-depth: 1
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        ref: ${{ inputs.branch }}
    - name: Build Docs
      working-directory: meshery-cloud
      run:  |
        npm i -g @redocly/cli@latest
        make docs-build
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Setup UI Dependencies
      working-directory: meshery-cloud
      run: make ui-setup
    - name: Build RTK Query Codegen
      working-directory: meshery-cloud
      run: make ui-api-codegen
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v5
      with:
          images: layer5/meshery-cloud
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{inputs.release-environment}}-{{sha}}
            type=raw,value=${{inputs.release-environment}}-{{tag}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=${{inputs.release-environment}}-latest
            type=raw,value=${{inputs.release-environment}}-${{inputs.release-version}}
            type=raw,value=${{inputs.release-environment}}-${{env.GIT_VERSION}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}        
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: meshery-cloud
        push: true
        build-args: |
          ENVIRONMENT=stg
          GIT_VERSION=${{inputs.release-environment}}-${{inputs.release-version}}
          RELEASE_CHANNEL=${{inputs.release-environment}}
          TOKEN=${{ secrets.GLOBAL_TOKEN }}
        tags: ${{ steps.meta.outputs.tags }}
        platforms: linux/amd64
    - name: Deploy staging
      if: success()
      uses: appleboy/ssh-action@master
      env:
          GIT_VERSION: ${{inputs.release-version}}
          GIT_COMMITSHA: ${{ github.sha }}
      with:
        host: ${{ secrets.MESHERY_CLOUD_AWS_STG_HOST }}
        username: ${{ secrets.MESHERY_CLOUD_AWS_PROD_USERNAME }}
        key: ${{ secrets.MESHERY_CLOUD_AWS_PROD_KEY }}
        port: 22
        envs: GIT_VERSION,GIT_COMMITSHA
        script: |
          sudo su
          cd meshery-cloud
          sudo su - -c "git pull https://l5io:${{ secrets.GH_ACCESS_TOKEN }}@github.com/layer5io/meshery-cloud"
          docker pull layer5/meshery-cloud:staging-$GIT_VERSION
          sudo su - -c "whoami"
          make stg-deploy GIT_VERSION=$GIT_VERSION
          docker system prune -f
          docker image prune -a -f
  prod:
    needs: update-doc-release-version
    if: always() && inputs.release-environment == 'production'
    name: Production - Docker build and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Meshery Cloud code
      uses: actions/checkout@v4
      with:
        repository: layer5io/meshery-cloud
        path: meshery-cloud
        fetch-depth: 1
        token: ${{ secrets.GH_ACCESS_TOKEN }}
    - name: Build Docs
      working-directory: meshery-cloud
      run:  |
        npm i -g @redocly/cli@latest
        make docs-build
    - name: Setup UI Dependencies
      working-directory: meshery-cloud
      run: make ui-setup
    - name: Build RTK Query Codegen
      working-directory: meshery-cloud
      run: make ui-api-codegen
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
          images: layer5/meshery-cloud
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{inputs.release-environment}}-{{sha}}
            type=raw,value=${{inputs.release-environment}}-{{tag}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=${{inputs.release-environment}}-latest
            type=raw,value=${{inputs.release-environment}}-${{inputs.release-version}}
            type=raw,value=${{inputs.release-environment}}-${{env.GIT_VERSION}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}        
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: meshery-cloud
        push: true
        build-args: |
          ENVIRONMENT=prod
          GIT_VERSION=${{inputs.release-environment}}-${{inputs.release-version}}
          RELEASE_CHANNEL=${{inputs.release-environment}}
          TOKEN=${{ secrets.GLOBAL_TOKEN }}
        tags: ${{ steps.meta.outputs.tags }}
        platforms: linux/amd64
    # - name: Deploy production in AWS EC2
    #   uses: appleboy/ssh-action@master
    #   env:
    #       GIT_VERSION: ${{inputs.release-version}}
    #       GIT_COMMITSHA: ${{ github.sha }}
    #   with:
    #     host: ${{ secrets.MESHERY_CLOUD_AWS_PROD_HOST }}
    #     username: ${{ secrets.MESHERY_CLOUD_AWS_PROD_USERNAME }}
    #     key: ${{ secrets.MESHERY_CLOUD_AWS_PROD_KEY }}
    #     port: 22
    #     envs: GIT_VERSION,GIT_COMMITSHA
    #     script: |
    #       sudo su
    #       sudo su - -c "whoami"
    #       echo $GIT_VERSION
    #       cd meshery-cloud
    #       sudo su - -c "git pull https://l5io:${{ secrets.GH_ACCESS_TOKEN }}@github.com/layer5io/meshery-cloud"
    #       sudo ./install/scripts/git-pull.sh
    #       docker pull layer5/meshery-cloud:production-$GIT_VERSION
    #       make prod-deploy GIT_VERSION=$GIT_VERSION
    #       docker system prune -f
    #       docker image prune -a -f
    - name: Deploy production on metal03
      uses: appleboy/ssh-action@master
      env:
          GIT_VERSION: ${{inputs.release-version}}
      with:
        host: ${{ secrets.METAL03_HOST }}
        username: ${{ secrets.METAL03_USERNAME }}
        key: ${{ secrets.METAL03_KEY }}
        port: 22
        envs: GIT_VERSION
        script: |
          helm upgrade -f ~/aws-m03/meshery-cloud/install/kubernetes/helm/layer5-cloud/values.yaml layer5 ~/aws-m03/meshery-cloud/install/kubernetes/helm/layer5-cloud/ -n prod-cloud --set=image.tag=production-$GIT_VERSION --set-file 'kratos.kratos.emailTemplates.recovery.valid.subject'=./aws-m03/meshery-cloud/config/email-templates/valid/email-recover-subject.body.gotmpl --set-file 'kratos.kratos.emailTemplates.recovery.valid.body'=./aws-m03/meshery-cloud/config/email-templates/valid/email-recover.body.gotmpl --set-file 'kratos.kratos.emailTemplates.verification.valid.subject'=./aws-m03/meshery-cloud/config/email-templates/valid/email-verify-subject.body.gotmpl --set-file 'kratos.kratos.emailTemplates.verification.valid.body'=./aws-m03/meshery-cloud/config/email-templates/valid/email-verify.body.gotmpl
          kubectl apply -f ./aws-m03/ingress.yaml
